#---> MODELO LLAMADAS <---

# 1) Estudio de las tablas <---

# Tabla STG_CONTACTOS_IVR
SELECT COUNT(*) TOTAL_REGISTROS
, SUM(CASE WHEN LENGTH(TRIM(ID))<>0 THEN 1 ELSE 0 END) TOTAL_ID
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ID))<>0 THEN ID ELSE 0  END) TOTAL_DISTINTOS_ID
, SUM(CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>0 THEN 1 ELSE 0 END) TOTAL_PHONE_NUMBER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>0 THEN PHONE_NUMBER ELSE 0  END) TOTAL_DISTINTOS_PHONE_NUMBER
, SUM(CASE WHEN LENGTH(TRIM(START_DATETIME))<>0 THEN 1 ELSE 0 END) TOTAL_START_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DATETIME))<>0 THEN START_DATETIME ELSE 0  END) TOTAL_DISTINTOS_START_DATETIME
, SUM(CASE WHEN LENGTH(TRIM(END_DATETIME))<>0 THEN 1 ELSE 0 END) TOTAL_END_DATETIME
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DATETIME))<>0 THEN END_DATETIME ELSE 0  END) TOTAL_DISTINTOS_END_DATETIME
, SUM(CASE WHEN LENGTH(TRIM(SERVICE))<>0 THEN 1 ELSE 0 END) TOTAL_SERVICE
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(SERVICE))<>0 THEN SERVICE ELSE 0  END) TOTAL_DISTINTOS_SERVICE
, SUM(CASE WHEN LENGTH(TRIM(FLG_TRANSFER))<>0 THEN 1 ELSE 0 END) TOTAL_FLG_TRANSFER
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(FLG_TRANSFER))<>0 THEN FLG_TRANSFER ELSE 0  END) TOTAL_DISTINTOS_FLG_TRANSFER
, SUM(CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN 1 ELSE 0 END) TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT))<>0 THEN AGENT ELSE 0  END) TOTAL_DISTINTOS_AGENT
FROM STAGE.STG_CONTACTOS_IVR;


# 2) Creación de tablas en ODS <---

# 2.1 Creación tabla dimensión departamentos 
DROP TABLE IF EXISTS ODS.ODS_DM_DEPARTAMENTOS_CC;
CREATE TABLE ODS.ODS_DM_DEPARTAMENTOS_CC
(ID_DEPARTAMENTO_CC INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_DEPARTAMENTO_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

ANALYZE TABLE ODS.ODS_DM_DEPARTAMENTOS_CC;

# 2.2 Creación tabla dimensión agentes
DROP TABLE IF EXISTS ODS.ODS_DM_AGENTES_CC;
CREATE TABLE ODS.ODS_DM_AGENTES_CC
(ID_AGENTE_CC INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_AGENTE_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

ANALYZE TABLE ODS.ODS_DM_AGENTES_CC;

# 2.3 Creación tabla hechos llamadas 
DROP TABLE IF EXISTS ODS.ODS_HC_LLAMADAS;
CREATE TABLE ODS.ODS_HC_LLAMADAS
(ID_LLAMADA INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
, ID_IVR INT(11)
, TELEFONO_LLAMADA BIGINT(20)
, FC_INICIO_LLAMADA DATETIME
, FC_FIN_LLAMADA DATETIME
, ID_DEPARTAMENTO_CC INT(10) UNSIGNED
, FLG_TRANSFERIDO BOOLEAN
, ID_AGENTE_CC INT(10) UNSIGNED
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

ANALYZE TABLE ODS.ODS_HC_LLAMADAS;


# 3) Creación FKs <---

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llamad_depart_idx (ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_depart FOREIGN KEY(ID_DEPARTAMENTO_CC)
   REFERENCES ODS.ODS_DM_DEPARTAMENTOS_CC(ID_DEPARTAMENTO_CC);

ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_llamad_agent_idx (ID_AGENTE_CC ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_agent FOREIGN KEY(ID_AGENTE_CC)
   REFERENCES ODS.ODS_DM_AGENTES_CC(ID_AGENTE_CC);


# 4) Poblamos el modelo <---

# 4.1 Poblamos tabla dimensión departamentos
INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(SERVICE)) DEPARTAMENTO_CC
, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR DEPARTAMENTO
WHERE TRIM(SERVICE)<>'';
INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC VALUES (999,'DESCONOCIDO', NOW(),NOW());
INSERT INTO ODS.ODS_DM_DEPARTAMENTOS_CC VALUES (998,'NO APLICA', NOW(),NOW());
COMMIT;

ANALYZE TABLE ODS.ODS_DM_DEPARTAMENTOS_CC;

# 4.2 Poblamos tabla dimensión agentes
INSERT INTO ODS.ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)) DEPARTAMENTO_CC
, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR DEPARTAMENTO
WHERE TRIM(AGENT)<>'';
INSERT INTO ODS.ODS_DM_AGENTES_CC VALUES (9999,'DESCONOCIDO', NOW(),NOW());
INSERT INTO ODS.ODS_DM_AGENTES_CC VALUES (9998,'NO APLICA', NOW(),NOW());
COMMIT;

ANALYZE TABLE ODS.ODS_DM_AGENTES_CC;

# 4.3 Poblamos tabla hechos llamadas
INSERT INTO ODS.ODS_HC_LLAMADAS
(ID_IVR
, TELEFONO_LLAMADA
, FC_INICIO_LLAMADA
, FC_FIN_LLAMADA
, ID_DEPARTAMENTO_CC
, FLG_TRANSFERIDO
, ID_AGENTE_CC
, FC_INSERT
, FC_MODIFICACION)
SELECT SCIV.ID
, CASE WHEN TRIM(SCIV.PHONE_NUMBER)<>'' THEN REPLACE(SCIV.PHONE_NUMBER,'-','') ELSE -1 END TELEFONO_LLAMADA
, CASE WHEN TRIM(SCIV.START_DATETIME)<>'' THEN STR_TO_DATE(LEFT(SCIV.START_DATETIME,19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d') END FC_INICIO_LLAMADA
, CASE WHEN TRIM(SCIV.END_DATETIME)<>'' THEN STR_TO_DATE(LEFT(SCIV.END_DATETIME,19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('9999-12-31','%Y-%m-%d') END FC_FIN_LLAMADA
, OODC.ID_DEPARTAMENTO_CC
, IF(UPPER(SCIV.FLG_TRANSFER)='FALSE', FALSE, TRUE) AS FLG_TRANSFERIDO
, OODA.ID_AGENTE_CC
, NOW()
, NOW()
FROM STAGE.STG_CONTACTOS_IVR SCIV
INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC OODC ON CASE WHEN TRIM(SCIV.SERVICE)<>'' THEN UPPER(TRIM(SCIV.SERVICE)) ELSE 'DESCONOCIDO' END=OODC.DE_DEPARTAMENTO_CC
INNER JOIN ODS.ODS_DM_AGENTES_CC OODA ON CASE WHEN TRIM(SCIV.AGENT)<>'' THEN UPPER(TRIM(SCIV.AGENT)) ELSE 'DESCONOCIDO' END=OODA.DE_AGENTE_CC;
COMMIT;

ANALYZE TABLE ODS.ODS_HC_FACTURAS;
